### ISSUE TITLE
Comparison to `nobrainer`

### ISSUE THREAD

**Issue by HippocampusGirl** [NeuroAI-HD/HD-BET#1]
A project that started, as far as I can tell, around the same time as yours is https://github.com/neuronets/nobrainer. Have you ever done a performance comparison?

**Comment by FabianIsensee** [comment]
Hi, not really. The HD-BET project is concluded from our end and we are not working on a successor. Have you tried both tools?

**Comment by HippocampusGirl** [comment]
Thank you for the response! Yeah, I have tried a few different ones. While HD-BET was great for it's time, newer tools like [SynthSeg](https://github.com/BBillot/SynthSeg) greatly outperform it in my testing.

**Comment by FabianIsensee** [comment]
Interesting, thanks for the feedback!
